id: P000739
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:16.092022
source_metadata:
  id: bdr:W1KG14652
  title: བདེ་མཆོག་ལྷན་སྐྱེས་ལྷ་ལྔའི་དྲིལ་བུའི་ཞལ་ལུང་།
  author: ''
  volumes:
    01acb98a8a7f4749b2232035a5a3d94b:
      image_group_id: I1KG15731
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
