id: P000739
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14652
  title: བདེ་མཆོག་ལྷན་སྐྱེས་ལྷ་ལྔའི་དྲིལ་བུའི་ཞལ་ལུང་།
  author: ''
  volumes:
    01acb98a8a7f4749b2232035a5a3d94b:
      image_group_id: I1KG15731
      title: ''
      volume_number: 1
      total_pages: 128
